{
 "title": "Golden Signals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(starlette_requests_total,method)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(starlette_requests_total{method=~\"$method\"},path_template)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "heatmap",
   "description": "Хитмапа. По оси Y отображена задержка запросов. По оси X время, в которое был произведен метрик. А их пересечение - это количество запросов, который отработали с той или иной задержкой",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(starlette_requests_processing_time_seconds_bucket{method=~\"$method\", path_template=~\"$path\"}) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Количество запросов в секунде на каждый endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{method=~\"$method\", path_template=~\"$path\"}[5m])) by(path_template)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Количество ошибок, сгруппированных по (method, endpoint) за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(starlette_exceptions_total{method=~\"$method\", path_template=~\"$path\"}[5m])",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Saturation (Memory)",
   "type": "timeseries",
   "description": "Количество запросов в секунде на каждый endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Saturation (CPU)",
   "type": "timeseries",
   "description": "Количество запросов в секунде на каждый endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}